# Generated by Django 6.0.6 on 2026-07-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0002_parish_delete_parroquia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.parish', verbose_name='parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('doctrinal_guide', models.TextField(blank=True, max_length=500, verbose_name='guía doctrinal')),
                ('order', models.IntegerField(verbose_name='orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coro.project', verbose_name='proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50, verbose_name='instrumento/voz')),
                ('audio_file', models.FileField(upload_to='audio/', verbose_name='archivo')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coro.song', verbose_name='canción')),
            ],
        ),
    ]
