# Generated by Django 6.0.6 on 2026-07-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Canción', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='voicetrack',
            options={'verbose_name': 'Maqueta de voz', 'verbose_name_plural': 'Maquetas de voz'},
        ),
    ]
