# Generated by Django 6.0.6 on 2026-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
