# Generated by Django 6.0.6 on 2026-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=400)),
                ('direccion_iglesia', models.CharField(max_length=80)),
                ('direccion_oficina', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario_misas', models.TextField()),
                ('sello_credencial', models.BooleanField(default=False)),
                ('info_peregrinos', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('logotipo', models.ImageField(blank=True, upload_to='')),
                ('activa', models.BooleanField(default=True)),
                ('color_primario', models.CharField(max_length=7)),
            ],
        ),
    ]
