# Generated by Django 6.0.6 on 2026-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('description', models.TextField(max_length=400, verbose_name='descripción')),
                ('church_dir', models.CharField(max_length=80, verbose_name='dirección iglesia')),
                ('office_dir', models.CharField(blank=True, max_length=80, verbose_name='dirección oficina')),
                ('phone', models.CharField(max_length=12, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mass_schedule', models.TextField(verbose_name='horario misas')),
                ('pilgrim_stamp', models.BooleanField(default=False, verbose_name='sello peregrinos')),
                ('pilgrim_info', models.TextField(blank=True, verbose_name='información peregrinos')),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Parroquia',
        ),
    ]
