# Generated by Django 6.0.6 on 2026-07-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Parroquia', 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='imagen')),
                ('date', models.DateField(verbose_name='fecha')),
                ('author', models.CharField(blank=True, verbose_name='autor')),
                ('published', models.BooleanField(default=False, verbose_name='visible')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.parish', verbose_name='parroquia')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
    ]
